### ISSUE TITLE
关于phoenix与benchmarksql联合测试的实例

### ISSUE THREAD

**Issue by woshihaichong** [co2y/algorithm#1]
同学您好，看到关于你在github上关于phoenix与benchmarksql进行tpcc的测试，对于配置过程中始终不能connection到phoenix的问题不能解决，是否可以提供关于benchmarksql在props.pg的配置改动的方案，谢谢

**Comment by co2y** [comment]
请参考[props.phoenix](https://github.com/co2y/TPC-C-on-Phoenix/blob/master/run/props.phoenix)，另这个issue似乎不应该在这。。
